package com.greatorator.tolkienmobs.datagen.loot;

import com.greatorator.tolkienmobs.TTMContent;
import com.greatorator.tolkienmobs.datagen.EntityGenerator;
import net.minecraft.data.loot.EntityLootTables;
import net.minecraft.entity.EntityType;
import net.minecraft.item.Items;
import net.minecraft.loot.*;
import net.minecraft.loot.conditions.EntityHasProperty;
import net.minecraft.loot.conditions.KilledByPlayer;
import net.minecraft.loot.functions.LootingEnchantBonus;
import net.minecraft.loot.functions.SetCount;
import net.minecraft.loot.functions.Smelt;

import java.util.HashSet;
import java.util.Set;

public class EntityLootGenerator extends EntityLootTables {
    private final Set<EntityType<?>> knownEntities = new HashSet<>();

    @Override
    protected void add(EntityType<?> entity, LootTable.Builder builder) {
        super.add(entity, builder);
        knownEntities.add(entity);
    }

    @Override
    protected void addTables() {
        // Ambient
        add(EntityGenerator.ENTITY_TTM_RAT.get(), noLoot());
        add(EntityGenerator.ENTITY_TTM_THRUSH.get(), fromEntityLootTable(EntityType.PARROT));
        add(EntityGenerator.ENTITY_TTM_SQUIRREL.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.TREE_ACORN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLDEN_TREE_ACORN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_FROG.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.INSECT.get())
                                    .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                    .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_SWARM.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.INSECT.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 5.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLDEN_INSECT.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer())));
        // Merchant
//        add(EntityGenerator.ENTITY_TTM_HUMAN.get(), LootTable.lootTable());
//        add(EntityGenerator.ENTITY_TTM_DWARF.get(), LootTable.lootTable());
//        add(EntityGenerator.ENTITY_TTM_ELVES.get(), LootTable.lootTable());
//        add(EntityGenerator.ENTITY_TTM_HOBBIT.get(), LootTable.lootTable());

        // Passive
        add(EntityGenerator.ENTITY_TTM_AUROCH.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FUR.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.LEATHER)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.BEEF)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_GOAT.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FUR.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.LEATHER)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.BEEF)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_MUMAKIL.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MUMAKIL_LEATHER.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 5.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 3.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.BEEF)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 5.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 3.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));

        // Monster
        add(EntityGenerator.ENTITY_TTM_GOBLIN.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.GUNPOWDER)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_BARROW.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_BRIGAND.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_DEEPCLAW.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.CRAM.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 12.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer()))));
        add(EntityGenerator.ENTITY_TTM_TREEENT.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.STICK)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.LOG_DEADWOOD.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.LEAFPILE_CULUMALDA.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.DRINK_ENT_DRAUGHT.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer()))));
        add(EntityGenerator.ENTITY_TTM_BRIGAND.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.AXE_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_FELLSPIRIT.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_SWAMPHAG.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.ENDER_PEARL)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.GLOWSTONE_DUST)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.SUGAR)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.REDSTONE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.SPIDER_EYE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.GLASS_BOTTLE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.GUNPOWDER)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_MIRKWOODSPIDER.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.COBWEB)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.SPIDER_EYE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer()))));
        add(EntityGenerator.ENTITY_TTM_HARADRIM.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_TROLL.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_WARG.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FUR.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 12.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_MORDORORC.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GROG.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.BONE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_HURON.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.STICK)
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.LOG_DEADWOOD.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.LEAFPILE_CULUMALDA.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GROG.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer()))));
        add(EntityGenerator.ENTITY_TTM_OATHBREAKER.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_ROMIEWALKER.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_DARKSIGIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_URUKHAI.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(2.0F, 6.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GROG.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.BONE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
        add(EntityGenerator.ENTITY_TTM_ELEMENTALGOLEM.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE_EARTH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE_AIR.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE_FIRE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE_WATER.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE_SUMMON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 15.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 5.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.BLOCK_MITHRIL.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.BLOCK_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.STONE)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer()))));
        add(EntityGenerator.ENTITY_TTM_MINOTAUR.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.AXE_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_BRONZE.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 12.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 6.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.GOLEM_STONE_AIR.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 4.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FUR.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer())));

        // Boss
        add(EntityGenerator.ENTITY_TTM_GOBLINKING.get(),
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.SWORD_MORGULIRON.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_COIN_SILVER.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F))))
                                .when(KilledByPlayer.killedByPlayer()))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONCOIN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.ITEM_FACTIONTOKEN.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(TTMContent.MONSTER_FLESH.get())
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 2.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .when(KilledByPlayer.killedByPlayer())))
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantRange.exactly(1))
                                .add(ItemLootEntry.lootTableItem(Items.GOLD_INGOT)
                                        .apply(SetCount.setCount(RandomValueRange.between(1.0F, 3.0F)))
                                        .apply(LootingEnchantBonus.lootingMultiplier(RandomValueRange.between(0.0F, 1.0F)))
                                        .apply(Smelt.smelted().when(EntityHasProperty.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE))))
                                .when(KilledByPlayer.killedByPlayer())));
    }

    public LootTable.Builder noLoot() {
        return LootTable.lootTable();
    }

    public LootTable.Builder fromEntityLootTable(EntityType<?> parent) {
        return LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(ConstantRange.exactly(1))
                        .add(TableLootEntry.lootTableReference(parent.getDefaultLootTable())));
    }

    @Override
    public Set<EntityType<?>> getKnownEntities() {
        return knownEntities;
    }

    public String getName() {
        return "Tolkien Tweaks - Mobs Edition Loot Tables - Entity";
    }
}
